PACKAGE_NAME="tc956x-dkms"
PACKAGE_VERSION="2025.11.04"

BUILT_MODULE_NAME[0]="tc956x_pcie_eth"
BUILT_MODULE_LOCATION[0]="drivers/net/ethernet/toshiba/tc956x/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/ethernet/toshiba/"

MAKE[0]="make -C ${kernel_source_dir} \
         CONFIG_TC956X_NET=m \
         CONFIG_TC956X_PF=y \
         CONFIG_TC956X_VF=n \
         CONFIG_TC956X_PCIE_GEN3_SETTING=y \
         CONFIG_TC956X_IOCTL_REG_RD_WR_ENABLE=y \
         KERNEL_DIR=${kernel_source_dir} \
         M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/drivers/net/ethernet/toshiba/tc956x"

AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL="^6\.([6]|1[2-7])"
